### PR TITLE
updated yarn to 1.16.0

### PR DESCRIPTION
**Pull request by mwahaworld**
updated Yarn to 1.16.0 to get the latest features / bug fixes from Yarn

### CODE REVIEW

**Comment by natemcmaster** [comment]
Thanks for the PR! Can you update the failing tests before I merge?

**Comment by mwahaworld** [comment]
@natemcmaster I've updated the failing test. there was no warnings to output so I removed the checks. I'm not sure if that particular test is still valuable, I'm hesitant to remove the test but I'll leave that up to you.

**Comment by natemcmaster** [comment]
Interesting, I'll take a closer look. Its possible yarn changed the output format for warnings

**Comment by natemcmaster** [comment]
Looks like yarn still issues the warnings, but there are 6 warnings, not 2, in the new version of Yarn. I've updated the test to reflect this.

Thanks for the contribution! I'll get this uploaded to nuget.org today.

**Pull request merged**
